#!/usr/bin/env python3
import re, sys, os, subprocess

if len(sys.argv) < 3:
    print("Usage: gen_symbol_table.py <elf> <output.c>")
    sys.exit(1)

elf = sys.argv[1]
out_c = sys.argv[2]
out_h = os.path.splitext(out_c)[0] + ".h"  # 自动生成同名 .h 文件

# 调用 arm-none-eabi-nm
result = subprocess.run(["arm-none-eabi-nm", "--numeric-sort", elf],
                        stdout=subprocess.PIPE, text=True)

lines = result.stdout.splitlines()
symbols = []

for line in lines:
    m = re.match(r"([0-9a-fA-F]+) [tT] (\S+)", line)
    if m:
        addr = int(m.group(1), 16)
        name = m.group(2)
        symbols.append((addr, name))

# 生成 .c 文件
with open(out_c, "w") as f:
    f.write("// Auto-generated by gen_symbol_table.py\n")
    f.write("#include <stdint.h>\n")
    f.write(f'#include "{os.path.basename(out_h)}"\n\n')
    f.write("const symbol_entry_t symbol_table[] = {\n")
    for addr, name in symbols:
        f.write(f"  {{0x{addr:08X}, \"{name}\"}},\n")
    f.write("};\n\n")
    f.write("const int symbol_count = sizeof(symbol_table)/sizeof(symbol_table[0]);\n")

# 生成 .h 文件
with open(out_h, "w") as f:
    f.write("// Auto-generated by gen_symbol_table.py\n")
    f.write("#ifndef SYMBOL_TABLE_H\n")
    f.write("#define SYMBOL_TABLE_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write("typedef struct {\n")
    f.write("    uint32_t addr;\n")
    f.write("    const char *name;\n")
    f.write("} symbol_entry_t;\n\n")
    f.write("extern const symbol_entry_t symbol_table[];\n")
    f.write("extern const int symbol_count;\n\n")
    f.write("#endif // SYMBOL_TABLE_H\n")

print(f"Generated {out_c} and {out_h} with {len(symbols)} symbols.")
