// Auto-generated by gen_symbol_table.py
#ifndef SYMBOL_TABLE_H
#define SYMBOL_TABLE_H

#include <stdint.h>

typedef struct {
    uint32_t addr;
    const char *name;
} symbol_entry_t;

extern const symbol_entry_t symbol_table[];
extern const int symbol_count;

#endif // SYMBOL_TABLE_H
